// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT WifiItems

lv_obj_t * ui_WifiItems_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_WifiItems;
    cui_WifiItems = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_WifiItems);
    lv_obj_set_width(cui_WifiItems, lv_pct(80));
    lv_obj_set_height(cui_WifiItems, lv_pct(20));
    lv_obj_set_align(cui_WifiItems, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(cui_WifiItems, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_WifiItems, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_WifiItems, lv_color_hex(0xA4A4A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_WifiItems, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_WifiItems, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_WifiItems, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_x(cui_WifiItems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_y(cui_WifiItems, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_WifiItems, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_WifiItems, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_Label3;
    cui_Label3 = lv_label_create(cui_WifiItems);
    lv_obj_set_width(cui_Label3, lv_pct(80));   /// 1
    lv_obj_set_height(cui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label3, "Text");

    lv_obj_t * cui_Button2;
    cui_Button2 = lv_button_create(cui_WifiItems);
    lv_obj_set_width(cui_Button2, lv_pct(20));
    lv_obj_set_height(cui_Button2, lv_pct(80));
    lv_obj_set_align(cui_Button2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Button2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Button2, lv_color_hex(0xC9C9C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t * icon_label = lv_label_create(cui_Button2);
    lv_label_set_text(icon_label, LV_SYMBOL_EDIT); // Ho?c d?ng "i" n?u kh?ng mu?n symbol

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_WIFIITEMS_NUM);
    children[UI_COMP_WIFIITEMS_WIFIITEMS] = cui_WifiItems;
    children[UI_COMP_WIFIITEMS_LABEL3] = cui_Label3;
    children[UI_COMP_WIFIITEMS_BUTTON2] = cui_Button2;
    lv_obj_add_event_cb(cui_WifiItems, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_WifiItems, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_WifiItems, ui_event_WifiSelected, LV_EVENT_ALL, NULL);
    ui_comp_WifiItems_create_hook(cui_WifiItems);
    return cui_WifiItems;
}

