// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_WIFIITEMS_H
#define _UI_COMP_WIFIITEMS_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT WifiItems
#define UI_COMP_WIFIITEMS_WIFIITEMS 0
#define UI_COMP_WIFIITEMS_LABEL3 1
#define UI_COMP_WIFIITEMS_BUTTON2 2
#define _UI_COMP_WIFIITEMS_NUM 3
lv_obj_t * ui_WifiItems_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
