// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_BRIGHTNESSAJUSTSCREEN_H
#define UI_BRIGHTNESSAJUSTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BrightNessAjustScreen
extern void ui_BrightNessAjustScreen_screen_init(void);
extern void ui_BrightNessAjustScreen_screen_destroy(void);
extern void ui_event_BrightNessAjustScreen(lv_event_t * e);
extern lv_obj_t * ui_BrightNessAjustScreen;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_BrightnessValue;
extern void ui_event_BrightnessSlider(lv_event_t * e);
extern lv_obj_t * ui_BrightnessSlider;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BrightNessAjustScreen;
extern lv_obj_t * uic_BrightnessValue;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

