// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MENUSCREEN_H
#define UI_MENUSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MenuScreen
extern void ui_MenuScreen_screen_init(void);
extern void ui_MenuScreen_screen_destroy(void);
extern lv_obj_t * ui_MenuScreen;
extern lv_obj_t * ui_ButtonMenuContainer;
extern void ui_event_Settingbutton(lv_event_t * e);
extern lv_obj_t * ui_Settingbutton;
extern void ui_event_DisplayButton(lv_event_t * e);
extern lv_obj_t * ui_DisplayButton;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ButtonMenuContainer;
extern lv_obj_t * uic_Settingbutton;
extern lv_obj_t * uic_DisplayButton;
extern lv_obj_t * uic_BrightnessButton;
extern lv_obj_t * uic_NewFeature;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

