// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_DisplayButton;
lv_obj_t * uic_Settingbutton;
lv_obj_t * uic_ButtonMenuContainer;
lv_obj_t * ui_MenuScreen = NULL;
lv_obj_t * ui_ButtonMenuContainer = NULL;
lv_obj_t * ui_Settingbutton = NULL;
lv_obj_t * ui_DisplayButton = NULL;
// event funtions
void ui_event_Settingbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_WifiScreen_screen_init);
    }
}

void ui_event_DisplayButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WeatherScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WeatherScreen_screen_init);
    }
}

// build funtions

void ui_MenuScreen_screen_init(void)
{
    ui_MenuScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_MenuScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MenuScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_ButtonMenuContainer = lv_obj_create(ui_MenuScreen);
    lv_obj_remove_style_all(ui_ButtonMenuContainer);
    lv_obj_set_width(ui_ButtonMenuContainer, lv_pct(100));
    lv_obj_set_height(ui_ButtonMenuContainer, lv_pct(30));
    lv_obj_set_align(ui_ButtonMenuContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ButtonMenuContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ButtonMenuContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ButtonMenuContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Settingbutton = lv_button_create(ui_ButtonMenuContainer);
    lv_obj_set_width(ui_Settingbutton, lv_pct(30));
    lv_obj_set_height(ui_Settingbutton, lv_pct(100));
    lv_obj_set_align(ui_Settingbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settingbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Settingbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settingbutton, lv_color_hex(0xC4C4C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settingbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t* label = lv_label_create(ui_Settingbutton);
    lv_label_set_text(label, LV_SYMBOL_SETTINGS);
    lv_obj_center(label);
    //lv_obj_set_style_text_font(label, LV_FONT_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_text_color(label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_text_opa(label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_text_font(label, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT); // Set font size to fit button

    ui_DisplayButton = lv_button_create(ui_ButtonMenuContainer);
    lv_obj_set_width(ui_DisplayButton, lv_pct(30));
    lv_obj_set_height(ui_DisplayButton, lv_pct(100));
    lv_obj_set_align(ui_DisplayButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DisplayButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_DisplayButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DisplayButton, lv_color_hex(0xC4C4C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DisplayButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t* label1 = lv_label_create(ui_DisplayButton);
    lv_label_set_text(label1, LV_SYMBOL_HOME);
    lv_obj_center(label1);

    lv_obj_add_event_cb(ui_Settingbutton, ui_event_Settingbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DisplayButton, ui_event_DisplayButton, LV_EVENT_ALL, NULL);
    uic_ButtonMenuContainer = ui_ButtonMenuContainer;
    uic_Settingbutton = ui_Settingbutton;
    uic_DisplayButton = ui_DisplayButton;

}

void ui_MenuScreen_screen_destroy(void)
{
    if(ui_MenuScreen) lv_obj_del(ui_MenuScreen);

    // NULL screen variables
    ui_MenuScreen = NULL;
    uic_ButtonMenuContainer = NULL;
    ui_ButtonMenuContainer = NULL;
    uic_Settingbutton = NULL;
    ui_Settingbutton = NULL;
    uic_DisplayButton = NULL;
    ui_DisplayButton = NULL;

}
