// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_WEATHERSCREEN_H
#define UI_WEATHERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WeatherScreen
extern void ui_WeatherScreen_screen_init(void);
extern void ui_WeatherScreen_screen_destroy(void);
extern void ui_event_WeatherScreen(lv_event_t * e);
extern lv_obj_t * ui_WeatherScreen;
extern lv_obj_t * ui_DateTimeContainer;
extern lv_obj_t * ui_TimeGroup;
extern lv_obj_t * ui_HourLable;
extern lv_obj_t * ui_Divider;
extern lv_obj_t * ui_MinuteLable;
extern lv_obj_t * ui_SecondLable;
extern lv_obj_t * ui_DateGroup1;
extern lv_obj_t * ui_DayOfWeekLable;
extern lv_obj_t * ui_DayLale;
extern lv_obj_t * ui_MonthLable;
extern lv_obj_t * ui_LocationGroup1;
extern lv_obj_t * ui_CityNameLable;
extern lv_obj_t * ui_LocationDataContainer;
extern lv_obj_t * ui_LatDataLable;
extern lv_obj_t * ui_LonDataLable;
extern lv_obj_t * ui_WeatherGoup;
extern lv_obj_t * ui_TempContainer;
extern lv_obj_t * ui_TempLable;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_HumidityContainer;
extern lv_obj_t * ui_HumidityDataLable;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WeatherScreen;
extern lv_obj_t * uic_DateTimeContainer;
extern lv_obj_t * uic_TimeGroup;
extern lv_obj_t * uic_HourLable;
extern lv_obj_t * uic_MinuteLable;
extern lv_obj_t * uic_DateGroup1;
extern lv_obj_t * uic_LocationGroup1;
extern lv_obj_t * uic_LatDataLable;
extern lv_obj_t * uic_WeatherGoup;
extern lv_obj_t * uic_TempLable;
extern lv_obj_t * uic_HumidityContainer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

