// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include "esp_log.h"
lv_obj_t * uic_WifiListContainer;
lv_obj_t * uic_WifiHeaderContainer;
lv_obj_t * uic_WifiScreen;
lv_obj_t * ui_WifiScreen = NULL;
lv_obj_t * ui_WifiHeaderContainer = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ScanSwitch = NULL;
lv_obj_t * ui_WifiListContainer = NULL;
lv_obj_t * ui_Spinner1 = NULL;
// event funtions
void ui_event_WifiScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MenuScreen_screen_init);
    }
}
void ui_event_ScanSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Event_ScanSwitch(e);
    }
}
void ui_event_WifiSelected(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_t* target = lv_event_get_target(e);
        lv_memset(st_WifiSelected.u1_ssid, 0, sizeof(st_WifiSelected.u1_ssid));
        lv_strcpy((char*) st_WifiSelected.u1_ssid, lv_label_get_text(ui_comp_get_child(target, UI_COMP_WIFIITEMS_LABEL3)));
        lv_label_set_text(ui_WifiSelectedName, (const char*)st_WifiSelected.u1_ssid);
        //ESP_LOGI("Wifi Select", "%s", st_WifiSelected.u1_ssid);
        _ui_screen_change(&ui_WifiTyping, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WifiTyping_screen_init);
    }
}

// build funtions

void ui_WifiScreen_screen_init(void)
{
    ui_WifiScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WifiScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_WifiScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WifiScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_WifiHeaderContainer = lv_obj_create(ui_WifiScreen);
    lv_obj_remove_style_all(ui_WifiHeaderContainer);
    lv_obj_set_width(ui_WifiHeaderContainer, lv_pct(100));
    lv_obj_set_height(ui_WifiHeaderContainer, lv_pct(20));
    lv_obj_set_align(ui_WifiHeaderContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiHeaderContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WifiHeaderContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiHeaderContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_WifiHeaderContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WifiHeaderContainer, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_WifiHeaderContainer);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "WIFI");
    lv_obj_set_style_pad_left(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScanSwitch = lv_switch_create(ui_WifiHeaderContainer);
    lv_obj_set_width(ui_ScanSwitch, 50);
    lv_obj_set_height(ui_ScanSwitch, 25);
    lv_obj_set_align(ui_ScanSwitch, LV_ALIGN_CENTER);

    ui_WifiListContainer = lv_obj_create(ui_WifiScreen);
    lv_obj_remove_style_all(ui_WifiListContainer);
    lv_obj_set_width(ui_WifiListContainer, lv_pct(100));
    lv_obj_set_height(ui_WifiListContainer, lv_pct(80));
    lv_obj_set_align(ui_WifiListContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiListContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WifiListContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiListContainer, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_WifiListContainer);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_add_event_cb(ui_ScanSwitch, ui_event_ScanSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiScreen, ui_event_WifiScreen, LV_EVENT_ALL, NULL);
    uic_WifiScreen = ui_WifiScreen;
    uic_WifiHeaderContainer = ui_WifiHeaderContainer;
    uic_WifiListContainer = ui_WifiListContainer;

}

void ui_WifiScreen_screen_destroy(void)
{
    if(ui_WifiScreen) lv_obj_del(ui_WifiScreen);

    // NULL screen variables
    uic_WifiScreen = NULL;
    ui_WifiScreen = NULL;
    uic_WifiHeaderContainer = NULL;
    ui_WifiHeaderContainer = NULL;
    ui_Label1 = NULL;
    ui_ScanSwitch = NULL;
    uic_WifiListContainer = NULL;
    ui_WifiListContainer = NULL;
    ui_Spinner1 = NULL;

}
