// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_WIFITYPING_H
#define UI_WIFITYPING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiTyping
extern void ui_WifiTyping_screen_init(void);
extern void ui_WifiTyping_screen_destroy(void);
extern lv_obj_t * ui_WifiTyping;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Container9;
extern void ui_event_TurnbackButotn(lv_event_t * e);
extern lv_obj_t * ui_TurnbackButotn;
extern lv_obj_t * ui_WifiSelectedName;
extern lv_obj_t * ui_TypingPasswordContainer;
extern lv_obj_t * ui_WifiTypingArea;
extern void ui_event_ConfirmButton(lv_event_t * e);
extern lv_obj_t * ConfirmPasswordButton;
extern lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WifiTyping;
extern lv_obj_t * uic_TurnbackButotn;
extern lv_obj_t * uic_WifiSelectedName;
extern lv_obj_t * uic_TypingPasswordContainer;
extern lv_obj_t * uic_WifiTypingArea;
extern void ui_event_WifiSelected(lv_event_t* e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

