// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_WifiTypingArea;
lv_obj_t * uic_TypingPasswordContainer;
lv_obj_t * uic_WifiSelectedName;
lv_obj_t * uic_TurnbackButotn;
lv_obj_t * uic_WifiTyping;
lv_obj_t * ui_WifiTyping = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_TurnbackButotn = NULL;
lv_obj_t * ui_WifiSelectedName = NULL;
lv_obj_t * ui_TypingPasswordContainer = NULL;
lv_obj_t * ui_WifiTypingArea = NULL;
lv_obj_t * ConfirmPasswordButton = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
// event funtions
void ui_event_TurnbackButotn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WifiScreen_screen_init);
    }
}

void ui_event_ConfirmButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Event_ConfirmPasswordButton(e);
    }
}


// build funtions
void ui_WifiTyping_screen_init(void)
{
    ui_WifiTyping = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WifiTyping, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_WifiTyping);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, lv_pct(100));
    lv_obj_set_height(ui_Container7, lv_pct(100));
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, lv_pct(100));
    lv_obj_set_height(ui_Container9, lv_pct(15));
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Container9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container9, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TurnbackButotn = lv_button_create(ui_Container9);
    lv_obj_set_width(ui_TurnbackButotn, lv_pct(20));
    lv_obj_set_height(ui_TurnbackButotn, lv_pct(100));
    lv_obj_set_align(ui_TurnbackButotn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TurnbackButotn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TurnbackButotn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TurnbackButotn, lv_color_hex(0xBCBCBC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TurnbackButotn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t* icon1 = lv_label_create(ui_TurnbackButotn);
    lv_label_set_text(icon1, LV_SYMBOL_LEFT);
    lv_obj_center(icon1);

    ui_WifiSelectedName = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_WifiSelectedName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiSelectedName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiSelectedName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiSelectedName, "text");

    ui_TypingPasswordContainer = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_TypingPasswordContainer);
    lv_obj_set_width(ui_TypingPasswordContainer, lv_pct(95));
    lv_obj_set_height(ui_TypingPasswordContainer, lv_pct(15));
    lv_obj_set_align(ui_TypingPasswordContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TypingPasswordContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TypingPasswordContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TypingPasswordContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiTypingArea = lv_textarea_create(ui_TypingPasswordContainer);
    lv_obj_set_width(ui_WifiTypingArea, lv_pct(70));
    lv_obj_set_height(ui_WifiTypingArea, lv_pct(100));
    lv_obj_set_align(ui_WifiTypingArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_WifiTypingArea, "Placeholder...");

    ConfirmPasswordButton = lv_button_create(ui_TypingPasswordContainer);
    lv_obj_set_width(ConfirmPasswordButton, lv_pct(20));
    lv_obj_set_height(ConfirmPasswordButton, lv_pct(100));
    lv_obj_set_align(ConfirmPasswordButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ConfirmPasswordButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ConfirmPasswordButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ConfirmPasswordButton, lv_color_hex(0xCFCFCF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ConfirmPasswordButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t* icon = lv_label_create(ConfirmPasswordButton);
    lv_obj_center(icon);
    lv_label_set_text(icon, LV_SYMBOL_OK);

    ui_Keyboard2 = lv_keyboard_create(ui_Container7);
    lv_obj_set_width(ui_Keyboard2, lv_pct(100));
    lv_obj_set_height(ui_Keyboard2, lv_pct(50));
    lv_obj_set_x(ui_Keyboard2, 10);
    lv_obj_set_y(ui_Keyboard2, 54);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_TurnbackButotn, ui_event_TurnbackButotn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ConfirmPasswordButton, ui_event_ConfirmButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_WifiTypingArea);
    uic_WifiTyping = ui_WifiTyping;
    uic_TurnbackButotn = ui_TurnbackButotn;
    uic_WifiSelectedName = ui_WifiSelectedName;
    uic_TypingPasswordContainer = ui_TypingPasswordContainer;
    uic_WifiTypingArea = ui_WifiTypingArea;

}

void ui_WifiTyping_screen_destroy(void)
{
    if(ui_WifiTyping) lv_obj_del(ui_WifiTyping);

    // NULL screen variables
    uic_WifiTyping = NULL;
    ui_WifiTyping = NULL;
    ui_Container7 = NULL;
    ui_Container9 = NULL;
    uic_TurnbackButotn = NULL;
    ui_TurnbackButotn = NULL;
    uic_WifiSelectedName = NULL;
    ui_WifiSelectedName = NULL;
    uic_TypingPasswordContainer = NULL;
    ui_TypingPasswordContainer = NULL;
    uic_WifiTypingArea = NULL;
    ui_WifiTypingArea = NULL;
    ConfirmPasswordButton = NULL;
    ui_Keyboard2 = NULL;

}
