// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_WIFISCREEN_H
#define UI_WIFISCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiScreen
extern void ui_WifiScreen_screen_init(void);
extern void ui_WifiScreen_screen_destroy(void);
extern lv_obj_t * ui_WifiScreen;
extern lv_obj_t * ui_WifiHeaderContainer;
extern lv_obj_t * ui_Label1;
extern void ui_event_ScanSwitch(lv_event_t * e);
extern lv_obj_t * ui_ScanSwitch;
extern lv_obj_t * ui_WifiListContainer;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WifiScreen;
extern lv_obj_t * uic_WifiHeaderContainer;
extern lv_obj_t * uic_WifiListContainer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

