// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_HumidityContainer;
lv_obj_t * uic_TempLable;
lv_obj_t * uic_WeatherGoup;
lv_obj_t * uic_LatDataLable;
lv_obj_t * uic_LocationGroup1;
lv_obj_t * uic_DateGroup1;
lv_obj_t * uic_MinuteLable;
lv_obj_t * uic_HourLable;
lv_obj_t * uic_TimeGroup;
lv_obj_t * uic_DateTimeContainer;
lv_obj_t * uic_WeatherScreen;
lv_obj_t * ui_WeatherScreen = NULL;
lv_obj_t * ui_DateTimeContainer = NULL;
lv_obj_t * ui_TimeGroup = NULL;
lv_obj_t * ui_HourLable = NULL;
lv_obj_t * ui_Divider = NULL;
lv_obj_t * ui_MinuteLable = NULL;
lv_obj_t * ui_SecondLable = NULL;
lv_obj_t * ui_DateGroup1 = NULL;
lv_obj_t * ui_DayOfWeekLable = NULL;
lv_obj_t * ui_DayLale = NULL;
lv_obj_t * ui_MonthLable = NULL;
lv_obj_t * ui_LocationGroup1 = NULL;
lv_obj_t * ui_CityNameLable = NULL;
lv_obj_t * ui_LocationDataContainer = NULL;
lv_obj_t * ui_LatDataLable = NULL;
lv_obj_t * ui_LonDataLable = NULL;
lv_obj_t * ui_WeatherGoup = NULL;
lv_obj_t * ui_TempContainer = NULL;
lv_obj_t * ui_TempLable = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_HumidityContainer = NULL;
lv_obj_t * ui_HumidityDataLable = NULL;
lv_obj_t * ui_Label3 = NULL;

static char weekday_buf[16];
static char weekday_prev[16];

// event funtions
void ui_event_WeatherScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MenuScreen_screen_init);
    }
}

// build funtions

void ui_WeatherScreen_screen_init(void)
{
    lv_subject_init_int(&subj_day, 0);
    lv_subject_init_int(&subj_month, 0);
    lv_subject_init_string(&subj_weekday, weekday_buf, weekday_prev, sizeof(weekday_buf), "");
    lv_subject_init_int(&subj_hour, 0);
    lv_subject_init_int(&subj_minute, 0);
    lv_subject_init_int(&subj_Second, 0);
    lv_subject_init_int(&subj_lat, 0);
    lv_subject_init_int(&subj_lon, 0);
    lv_subject_init_int(&subj_temperature, 0);
    lv_subject_init_int(&subj_humidity, 0);

    ui_WeatherScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WeatherScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DateTimeContainer = lv_obj_create(ui_WeatherScreen);
    lv_obj_remove_style_all(ui_DateTimeContainer);
    lv_obj_set_width(ui_DateTimeContainer, lv_pct(100));
    lv_obj_set_height(ui_DateTimeContainer, lv_pct(50));
    lv_obj_set_align(ui_DateTimeContainer, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_DateTimeContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DateTimeContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DateTimeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_DateTimeContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DateTimeContainer, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeGroup = lv_obj_create(ui_DateTimeContainer);
    lv_obj_remove_style_all(ui_TimeGroup);
    lv_obj_set_width(ui_TimeGroup, lv_pct(50));
    lv_obj_set_height(ui_TimeGroup, lv_pct(35));
    lv_obj_set_x(ui_TimeGroup, -1);
    lv_obj_set_y(ui_TimeGroup, -12);
    lv_obj_set_align(ui_TimeGroup, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TimeGroup, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TimeGroup, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_TimeGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HourLable = lv_label_create(ui_TimeGroup);
    lv_obj_set_width(ui_HourLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HourLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HourLable, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_HourLable, "16");
    lv_label_bind_text(ui_HourLable, &subj_hour, NULL);
    lv_obj_set_style_text_font(ui_HourLable, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Divider = lv_label_create(ui_TimeGroup);
    lv_obj_set_width(ui_Divider, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Divider, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Divider, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Divider, ":");
    lv_obj_set_style_text_font(ui_Divider, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinuteLable = lv_label_create(ui_TimeGroup);
    lv_obj_set_width(ui_MinuteLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinuteLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MinuteLable, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_MinuteLable, "25");
    lv_label_bind_text(ui_MinuteLable, &subj_minute, NULL);
    lv_obj_set_style_text_font(ui_MinuteLable, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Divider = lv_label_create(ui_TimeGroup);
    lv_obj_set_width(ui_Divider, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Divider, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Divider, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Divider, ":");
    lv_obj_set_style_text_font(ui_Divider, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SecondLable = lv_label_create(ui_TimeGroup);
    lv_obj_set_width(ui_SecondLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SecondLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SecondLable, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_SecondLable, "25");
    lv_label_bind_text(ui_SecondLable, &subj_Second, NULL);
    lv_obj_set_style_text_font(ui_SecondLable, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_DateGroup1 = lv_obj_create(ui_DateTimeContainer);
    lv_obj_remove_style_all(ui_DateGroup1);
    lv_obj_set_width(ui_DateGroup1, lv_pct(40));
    lv_obj_set_height(ui_DateGroup1, lv_pct(20));
    lv_obj_set_x(ui_DateGroup1, -1);
    lv_obj_set_y(ui_DateGroup1, -12);
    lv_obj_set_align(ui_DateGroup1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DateGroup1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DateGroup1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_DateGroup1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DayOfWeekLable = lv_label_create(ui_DateGroup1);
    lv_obj_set_width(ui_DayOfWeekLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DayOfWeekLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DayOfWeekLable, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_DayOfWeekLable, "SUN");
    lv_label_bind_text(ui_DayOfWeekLable, &subj_weekday, NULL);
    lv_obj_set_style_text_font(ui_DayOfWeekLable, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DayLale = lv_label_create(ui_DateGroup1);
    lv_obj_set_width(ui_DayLale, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DayLale, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DayLale, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_DayLale, "15");
    lv_label_bind_text(ui_DayLale, &subj_day, "%d");
    lv_obj_set_style_text_font(ui_DayLale, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MonthLable = lv_label_create(ui_DateGroup1);
    lv_obj_set_width(ui_MonthLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MonthLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MonthLable, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_MonthLable, "Jun");
    lv_label_bind_text(ui_MonthLable, &subj_month, "%02d");
    lv_obj_set_style_text_font(ui_MonthLable, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LocationGroup1 = lv_obj_create(ui_WeatherScreen);
    lv_obj_remove_style_all(ui_LocationGroup1);
    lv_obj_set_width(ui_LocationGroup1, lv_pct(40));
    lv_obj_set_height(ui_LocationGroup1, lv_pct(35));
    lv_obj_set_x(ui_LocationGroup1, -41);
    lv_obj_set_y(ui_LocationGroup1, -32);
    lv_obj_set_align(ui_LocationGroup1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_LocationGroup1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_LocationGroup1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LocationGroup1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LocationGroup1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LocationGroup1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LocationGroup1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CityNameLable = lv_label_create(ui_LocationGroup1);
    lv_obj_set_width(ui_CityNameLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CityNameLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CityNameLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CityNameLable, "Da Nang");

    ui_LocationDataContainer = lv_obj_create(ui_LocationGroup1);
    lv_obj_remove_style_all(ui_LocationDataContainer);
    lv_obj_set_width(ui_LocationDataContainer, lv_pct(100));
    lv_obj_set_height(ui_LocationDataContainer, lv_pct(40));
    lv_obj_set_align(ui_LocationDataContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LocationDataContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_LocationDataContainer, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LocationDataContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LatDataLable = lv_label_create(ui_LocationDataContainer);
    lv_obj_set_width(ui_LatDataLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LatDataLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LatDataLable, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_LatDataLable, "21.0285");
    lv_label_bind_text(ui_LatDataLable, &subj_lat, NULL);
    lv_obj_set_style_text_font(ui_LatDataLable, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LonDataLable = lv_label_create(ui_LocationDataContainer);
    lv_obj_set_width(ui_LonDataLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LonDataLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LonDataLable, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_LonDataLable, "105.8542");
    lv_label_bind_text(ui_LatDataLable, &subj_lon, NULL);
    lv_obj_set_style_text_font(ui_LonDataLable, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherGoup = lv_obj_create(ui_WeatherScreen);
    lv_obj_remove_style_all(ui_WeatherGoup);
    lv_obj_set_width(ui_WeatherGoup, lv_pct(30));
    lv_obj_set_height(ui_WeatherGoup, lv_pct(35));
    lv_obj_set_x(ui_WeatherGoup, 55);
    lv_obj_set_y(ui_WeatherGoup, -32);
    lv_obj_set_align(ui_WeatherGoup, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_WeatherGoup, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WeatherGoup, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_WeatherGoup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherGoup, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WeatherGoup, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WeatherGoup, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempContainer = lv_obj_create(ui_WeatherGoup);
    lv_obj_remove_style_all(ui_TempContainer);
    lv_obj_set_width(ui_TempContainer, lv_pct(100));
    lv_obj_set_height(ui_TempContainer, lv_pct(50));
    lv_obj_set_align(ui_TempContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TempContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TempContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TempContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempLable = lv_label_create(ui_TempContainer);
    lv_obj_set_width(ui_TempLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempLable, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_TempLable, "20");
    lv_label_bind_text(ui_TempLable, &subj_temperature, NULL);
    lv_obj_set_style_text_font(ui_TempLable, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_TempContainer);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "°C");

    ui_HumidityContainer = lv_obj_create(ui_WeatherGoup);
    lv_obj_remove_style_all(ui_HumidityContainer);
    lv_obj_set_width(ui_HumidityContainer, lv_pct(100));
    lv_obj_set_height(ui_HumidityContainer, lv_pct(50));
    lv_obj_set_align(ui_HumidityContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HumidityContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HumidityContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HumidityContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumidityDataLable = lv_label_create(ui_HumidityContainer);
    lv_obj_set_width(ui_HumidityDataLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityDataLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumidityDataLable, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_HumidityDataLable, "10");
    lv_label_bind_text(ui_HumidityDataLable, &subj_humidity, NULL);
    lv_obj_set_style_text_font(ui_HumidityDataLable, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_HumidityContainer);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "%");

    lv_obj_add_event_cb(ui_WeatherScreen, ui_event_WeatherScreen, LV_EVENT_ALL, NULL);
    uic_WeatherScreen = ui_WeatherScreen;
    uic_DateTimeContainer = ui_DateTimeContainer;
    uic_TimeGroup = ui_TimeGroup;
    uic_HourLable = ui_HourLable;
    uic_MinuteLable = ui_MinuteLable;
    uic_DateGroup1 = ui_DateGroup1;
    uic_LocationGroup1 = ui_LocationGroup1;
    uic_LatDataLable = ui_LatDataLable;
    uic_WeatherGoup = ui_WeatherGoup;
    uic_TempLable = ui_TempLable;
    uic_HumidityContainer = ui_HumidityContainer;

}

void ui_WeatherScreen_screen_destroy(void)
{
    if(ui_WeatherScreen) lv_obj_del(ui_WeatherScreen);

    // NULL screen variables
    uic_WeatherScreen = NULL;
    ui_WeatherScreen = NULL;
    uic_DateTimeContainer = NULL;
    ui_DateTimeContainer = NULL;
    uic_TimeGroup = NULL;
    ui_TimeGroup = NULL;
    uic_HourLable = NULL;
    ui_HourLable = NULL;
    ui_Divider = NULL;
    uic_MinuteLable = NULL;
    ui_MinuteLable = NULL;
    uic_DateGroup1 = NULL;
    ui_DateGroup1 = NULL;
    ui_DayOfWeekLable = NULL;
    ui_DayLale = NULL;
    ui_MonthLable = NULL;
    uic_LocationGroup1 = NULL;
    ui_LocationGroup1 = NULL;
    ui_CityNameLable = NULL;
    ui_LocationDataContainer = NULL;
    uic_LatDataLable = NULL;
    ui_LatDataLable = NULL;
    ui_LonDataLable = NULL;
    uic_WeatherGoup = NULL;
    ui_WeatherGoup = NULL;
    ui_TempContainer = NULL;
    uic_TempLable = NULL;
    ui_TempLable = NULL;
    ui_Label6 = NULL;
    uic_HumidityContainer = NULL;
    ui_HumidityContainer = NULL;
    ui_HumidityDataLable = NULL;
    ui_Label3 = NULL;

}
