// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "RamDef.h"
#include "esp_log.h"

lv_timer_t *timer;
lv_timer_t *timer1;
/**
 * @brief Callback function for WiFi scan state timer.
 *
 * This function is called periodically by a timer to check the current WiFi scan state.
 * It updates the UI spinner visibility and populates the WiFi list container with scan results
 * when scanning is done. If scanning is stopped, it clears the WiFi list container except for the spinner.
 *
 * @param timer Pointer to the lv_timer_t structure (can be NULL).
 */
static void Check_ScanState_Callback(lv_timer_t * timer)
{
	if (st_WifiStatus.u1_WifiScanState == U1ON)
	{
		if (st_WifiStatus.u1_WifiScanDone_F == U1FALSE) {
			lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);
		} else if (st_WifiStatus.u1_WifiScanDone_F == U1TRUE) {
			lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);
			if (timer) {
				lv_timer_del(timer);
				timer = NULL;
			}
			uint16_t num = (u2_WifiNum < SCAN_LIST_SIZE) ? u2_WifiNum : SCAN_LIST_SIZE;
			for (uint16_t i = 0; i < num; i++) {
				lv_obj_t *item = ui_WifiItems_create(ui_WifiListContainer);
				if (st_WifiInfo[i].u1_ssid[0] != '\0') {
					ESP_LOGI("WIFI", "SSID[%d]: %s", (int)i, st_WifiInfo[i].u1_ssid);
					lv_label_set_text(ui_comp_get_child(item, UI_COMP_WIFIITEMS_LABEL3), (const char*)st_WifiInfo[i].u1_ssid);
				} else {
					lv_label_set_text(ui_comp_get_child(item, UI_COMP_WIFIITEMS_LABEL3), "");
				}
			}
		}
	}
	else {
		if (timer) {
			lv_timer_del(timer);
			timer = NULL;
		}
		lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);
		uint32_t child_cnt = lv_obj_get_child_cnt(ui_WifiListContainer);
		for (uint32_t i = 0; i < child_cnt; ) {
			lv_obj_t *child = lv_obj_get_child(ui_WifiListContainer, i);
			if (child != ui_Spinner1) {
				lv_obj_del(child);
				child_cnt--;
			} else {
				i++;
			}
		}
	}
}

/**
 * @brief Event handler for the WiFi scan switch.
 *
 * This function is triggered when the user toggles the WiFi scan switch.
 * It updates the scan state variable and starts the scan state timer.
 *
 * @param e Pointer to the lv_event_t structure.
 */

void Event_ScanSwitch(lv_event_t * e)
{
	lv_obj_t * sw = lv_event_get_target(e);
	if(lv_obj_has_state(sw, LV_STATE_CHECKED)) {
		st_WifiStatus.u1_WifiScanState = WIFI_SCAN_ON;
	} else {
		st_WifiStatus.u1_WifiScanState = WIFI_SCAN_OFF;
	}
	timer = lv_timer_create(Check_ScanState_Callback, 100, NULL);
}

/**
 * @brief Callback function for WiFi connection status timer.
 *
 * This function is called periodically by a timer to checks the WiFi connection status and updates the message box UI accordingly.
 * It removes spinner and label children from the message box, then displays a success or error message.
 * The timer is deleted after the status is handled.
 *
 * @param a_timer Pointer to the lv_timer_t structure.
 */
void wifi_connect_status_cb(lv_timer_t * a_timer)
{
	lv_obj_t * mbox = (lv_obj_t *)lv_timer_get_user_data(a_timer);

	if ((st_WifiStatus.u1_WifiConnected_F == U1TRUE) || (st_WifiStatus.u1_WifiConnected_Fail_F == U1TRUE))
	{
		uint32_t child_cnt = lv_obj_get_child_cnt(mbox);
		for (uint32_t i = 0; i < child_cnt; ) {
			lv_obj_t *child = lv_obj_get_child(mbox, i);
			if (lv_obj_check_type(child, &lv_spinner_class)) {
				lv_obj_del(child);
				child_cnt--;
			} else {
				i++;
			}
		}

		lv_obj_t* content = lv_msgbox_get_content(mbox);
		child_cnt = lv_obj_get_child_cnt(content);

		for (uint32_t i = 0; i < child_cnt;) {
			lv_obj_t * child = lv_obj_get_child(content, i);
			if (lv_obj_check_type(child, &lv_label_class)) {
				lv_obj_del(child);
				child_cnt--;
			} else {
				i++;
			}
		}

		if (st_WifiStatus.u1_WifiConnected_F == U1TRUE) {
			lv_msgbox_add_title(mbox, "Success");
			lv_msgbox_add_text(mbox, "\nConnect Successfully!");
		} else if (st_WifiStatus.u1_WifiConnected_Fail_F == U1TRUE) {
			lv_msgbox_add_title(mbox, "Error");
			lv_msgbox_add_text(mbox, "\nWrong Password!");
		}
		lv_timer_del(a_timer);
	}
}

/**
 * @brief Event handler for the confirm password button.
 *
 * This function is called when the user presses the confirm password button.
 * It validates the entered password length and shows a warning if invalid.
 * If valid, it copies the password, shows a connecting message box with a spinner,
 * and starts a timer to check the WiFi connection status.
 *
 * @param e Pointer to the lv_event_t structure.
 */
void Event_ConfirmPasswordButton(lv_event_t * e)
{
	const char *password = lv_textarea_get_text(ui_WifiTypingArea);
	if (password == NULL || lv_strlen(password) < 8)
	{
		st_WifiSelected.u1_WifiPasswordValid_F = U1FALSE;
		lv_obj_t * mbox1 = lv_msgbox_create(lv_screen_active());
		lv_obj_clear_flag(mbox1, LV_OBJ_FLAG_SCROLLABLE);
		lv_obj_set_width(mbox1, LV_PCT(80));
		lv_obj_set_height(mbox1, LV_PCT(50));
		lv_msgbox_add_title(mbox1, "Warning");
		lv_msgbox_add_text(mbox1, "Password must be at least 8 characters long.");
		lv_msgbox_add_close_button(mbox1);
	}
	else
	{
		lv_strcpy((char*)st_WifiSelected.u1_password, password);
		st_WifiSelected.u1_WifiPasswordValid_F = U1TRUE;
		lv_obj_t * mbox1 = lv_msgbox_create(NULL);
		lv_obj_set_width(mbox1, LV_PCT(80));
		lv_obj_set_height(mbox1, LV_PCT(50));
		lv_msgbox_add_title(mbox1, "Connecting to WiFi");

		lv_obj_t * spinner = lv_spinner_create(mbox1);
		lv_obj_set_size(spinner, 40, 40);
		lv_obj_align(spinner, LV_ALIGN_CENTER, 0, 0);
		lv_spinner_set_anim_params(spinner, 1000, 60);
		lv_msgbox_add_text(mbox1, "\nConnecting...");

		timer1 = lv_timer_create(wifi_connect_status_cb, 200, mbox1);
		lv_msgbox_add_close_button(mbox1);
	}
}
