// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "RamDef.h"
#include "esp_log.h"

lv_timer_t *timer;
lv_timer_t *timer1;

static void Check_ScanState_Callback(lv_timer_t * timer)
{
	if (u1_WifiScanState == U1ON)
	{
		if (u1_WifiScanDone_F == U1OFF){
			lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);     /// Flags
		}else{
			lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);     /// Flags
			if (timer) {
				lv_timer_del(timer);
				timer = NULL;
			}
			uint16_t num = (u2_WifiNum < SCAN_LIST_SIZE) ? u2_WifiNum : SCAN_LIST_SIZE;
			for (uint16_t i = 0; i < num; i++) {
				lv_obj_t *item = ui_WifiItems_create(ui_WifiListContainer);
				if (st_WifiInfo[i].u1_ssid[0] != '\0') {
					ESP_LOGI("WIFI", "SSID[%d]: %s", (int)i, st_WifiInfo[i].u1_ssid);
					lv_label_set_text(ui_comp_get_child(item, UI_COMP_WIFIITEMS_LABEL3), (const char*)st_WifiInfo[i].u1_ssid);
				} else {
					lv_label_set_text(ui_comp_get_child(item, UI_COMP_WIFIITEMS_LABEL3), "");
				}
				}
			}
	}
	else{
		if (timer) {
			lv_timer_del(timer);
			timer = NULL;
		}
		lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);     /// Flags
		uint32_t child_cnt = lv_obj_get_child_cnt(ui_WifiListContainer);
		for (uint32_t i = 0; i < child_cnt; ) {
			lv_obj_t *child = lv_obj_get_child(ui_WifiListContainer, i);
			if (child != ui_Spinner1) {
				lv_obj_del(child);
				child_cnt--;
			} else {
				i++; // B? qua spinner
			}
		}
	}
	
}

void Event_ScanSwitch(lv_event_t * e)
{
	// Just set a flag, do not handle list here
	lv_obj_t * sw = lv_event_get_target(e); // Get the switch object
	if(lv_obj_has_state(sw, LV_STATE_CHECKED)) {
		u1_WifiScanState = WIFI_SCAN_ON; // Set WiFi scan state to ON
	} else {
		u1_WifiScanState = WIFI_SCAN_OFF; // Set WiFi scan state to OFF
	}
	// Start a one-shot timer to handle scan completion
	timer = lv_timer_create(Check_ScanState_Callback, 100, NULL);
}


// Create a timer to check connection status and update UI
static void wifi_connect_status_cb(lv_timer_t * timer1)
{
	lv_obj_t * mbox = (lv_obj_t *)lv_timer_get_user_data(timer1);

	if ((u1_WifiConnected_F == U1TRUE) || (u1_WifiConnected_Fail_F == U1TRUE)) 
	{
		// Remove all labels and spinners in the message box
		uint32_t child_cnt = lv_obj_get_child_cnt(mbox);
		for (uint32_t i = 0; i < child_cnt; ) {
			lv_obj_t *child = lv_obj_get_child(mbox, i);
			if (lv_obj_check_type(child, &lv_spinner_class)) {
				lv_obj_del(child);
				child_cnt--;
			} else {
				i++;
			}
		}

		lv_obj_t* content = lv_msgbox_get_content(mbox);
		child_cnt = lv_obj_get_child_cnt(content);

		for (uint32_t i = 0; i < child_cnt;) {
			lv_obj_t * child = lv_obj_get_child(content, i);

			if (lv_obj_check_type(child, &lv_label_class)) {
				lv_obj_del(child);
				// Kh?ng t?ng i v? s? l??ng child ?? gi?m
				child_cnt--;
			} else {
				i++;  // Kh?ng x?a => t?ng ch? s?
			}
		}

		if ((u1_WifiConnected_F == U1TRUE))
		{
			lv_msgbox_add_title(mbox, "Success");
			lv_msgbox_add_text(mbox, "\nConnect Successfully!");
		} else if (u1_WifiConnected_Fail_F == U1TRUE)
		{
			lv_msgbox_add_title(mbox, "Error");
			lv_msgbox_add_text(mbox, "\nWrong PassWord!");
		}
		lv_timer_del(timer1);
	}
}

void Event_ConfirmPasswordButton(lv_event_t * e)
{
	const char *password = lv_textarea_get_text(ui_WifiTypingArea);
	if (password == NULL || lv_strlen(password) < 8) 
	{
		st_WifiSelected.u1_WifiPasswordValid_F = U1FALSE; // Set password valid flag to FALSE
		lv_obj_t * mbox1 = lv_msgbox_create(lv_screen_active());
		lv_obj_clear_flag(mbox1, LV_OBJ_FLAG_SCROLLABLE); // Clear scrollable flag
		lv_obj_set_width(mbox1, LV_PCT(80)); // Set width to 80% of parent
		lv_obj_set_height(mbox1, LV_PCT(50)); // Set height to 30% of parent
		lv_msgbox_add_title(mbox1, "Warning");
		lv_msgbox_add_text(mbox1, "Password must be at least 8 characters long.");
		lv_msgbox_add_close_button(mbox1);
	}
	else 
	{
		lv_strcpy((char*)st_WifiSelected.u1_password, password);
		st_WifiSelected.u1_WifiPasswordValid_F = U1TRUE; // Set password valid flag to TRUE
		lv_obj_t * mbox1 = lv_msgbox_create(NULL);
		lv_obj_set_width(mbox1, LV_PCT(80)); // Set width to 80% of parent
		lv_obj_set_height(mbox1, LV_PCT(50)); // Set height to 30% of parent
		lv_msgbox_add_title(mbox1, "Connecting to WiFi");

		// Show spinner and "Connecting..." text initially
		lv_obj_t * spinner = lv_spinner_create(mbox1);
		lv_obj_set_size(spinner, 40, 40); // Set spinner size as needed
		lv_obj_align(spinner, LV_ALIGN_CENTER, 0, 0); // Center the spinner in the message box
		lv_spinner_set_anim_params(spinner, 1000, 60); // Set animation time and arc length
		lv_msgbox_add_text(mbox1, "\nConnecting...");

		// create callback to handle WiFi connection
		timer1 = lv_timer_create(wifi_connect_status_cb, 200, mbox1); // Check every 200ms
		lv_msgbox_add_close_button(mbox1);
	}
}
