// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Event_ScanSwitch(lv_event_t * e);
void Event_ConfirmPasswordButton(lv_event_t * e);
void event_BrightnessAdjust_Callback(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
